import {
  UtensilsCrossed,
  Coffee,
  Scissors,
  ShoppingBag,
  Dumbbell,
  Car,
  Briefcase,
  Heart,
  Store,
  Home,
  Building,
  Hammer,
  Wrench,
  GraduationCap,
  Stethoscope,
  Shield,
  Gavel,
  Camera,
  Palette,
  Music,
  MapPin,
  Plane,
  Bus,
  Truck,
  Ship,
  Phone,
  Wifi,
  Zap,
  Droplets,
  TreePine,
  Leaf,
  Flower,
  Dog,
  Cat,
  Fish,
  Baby,
  Users,
  Clock,
  CreditCard,
  DollarSign,
  Shirt,
  Glasses,
  Watch,
  Gem,
  Gift,
  Book,
  Gamepad2,
  Trophy,
  Target,
  Bike,
  Waves,
  Mountain,
  Tent,
  Compass,
  Star,
  Moon,
  Sun,
  Cloud,
  Pizza,
  Cake,
  IceCream,
  ChefHat,
  Utensils,
  Settings,
  Calculator,
  BriefcaseMedical,
  Pill,
  Cross,
  Church,
  Film,
  Monitor,
  Laptop,
  Smartphone,
  Mail,
  Calendar,
  Fuel,
  Bell,
  AlertTriangle,
} from "lucide-react";

export const buisnessTypeIcons: any[string] = {
  UtensilsCrossed: UtensilsCrossed,
  Coffee: Coffee,
  Scissors: Scissors,
  ShoppingBag: ShoppingBag,
  Dumbbell: Dumbbell,
  Car: Car,
  Briefcase: Briefcase,
  Heart: Heart,
  Store: Store,
  Home: Home,
  Building: Building,
  Hammer: Hammer,
  Wrench: Wrench,
  GraduationCap: GraduationCap,
  Stethoscope: Stethoscope,
  Shield: Shield,
  Gavel: Gavel,
  Camera: Camera,
  Palette: Palette,
  Music: Music,
  MapPin: MapPin,
  Plane: Plane,
  Bus: Bus,
  Truck: Truck,
  Ship: Ship,
  Phone: Phone,
  Wifi: Wifi,
  Zap: Zap,
  Droplets: Droplets,
  TreePine: TreePine,
  Leaf: Leaf,
  Flower: Flower,
  Dog: Dog,
  Cat: Cat,
  Fish: Fish,
  Baby: Baby,
  Users: Users,
  Clock: Clock,
  CreditCard: CreditCard,
  DollarSign: DollarSign,
  Shirt: Shirt,
  Glasses: Glasses,
  Watch: Watch,
  Gem: Gem,
  Ring: Gem,
  Gift: Gift,
  Book: Book,
  Gamepad2: Gamepad2,
  Trophy: Trophy,
  Target: Target,
  Bike: Bike,
  Waves: Waves,
  Mountain: Mountain,
  Tent: Tent,
  Compass: Compass,
  Star: Star,
  Moon: Moon,
  Sun: Sun,
  Cloud: Cloud,
  Pizza: Pizza,
  Cake: Cake,
  IceCream: IceCream,
  ChefHat: ChefHat,
  Utensils: Utensils,
  Settings: Settings,
  Calculator: Calculator,
  FirstAid: BriefcaseMedical,
  Pills: Pill,
  Cross: Cross,
  Church: Church,
  Film: Film,
  Monitor: Monitor,
  Laptop: Laptop,
  Smartphone: Smartphone,
  Mail: Mail,
  Calendar: Calendar,
  Fuel: Fuel,
  Bell: Bell,
  AlertTriangle: AlertTriangle,
};
